name: build

on: [push]

jobs:
  build-windows:
    strategy:
      matrix:
        target:
          - { triplet: 'x86-windows', arch: 'x86' }
          - { triplet: 'x64-windows', arch: 'x64' }

    runs-on: windows-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install dependencies
        run: vcpkg install lua:${{ matrix.target.triplet }} taglib:${{ matrix.target.triplet }}

      - name: configure lua-taglib ${{ matrix.target.arch }}
        run: 'cmake -B build-${{ matrix.target.arch }} -DCMAKE_BUILD_TYPE=Debug -DVCPKG_TARGET_TRIPLET=${{ matrix.target.triplet }}  -DVCPKG_TARGET_ARCHITECTURE=${{ matrix.target.arch }} -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake -S .'

      - name: build lua-taglib ${{ matrix.target.arch }}
        run: 'cmake --build build-${{ matrix.target.arch }} --config Debug'

  build-linux:
    strategy:
      matrix:
        taglib_version:
          - '1.0'
          - '1.1'
          - '1.2'
          - '1.3.1'
          - '1.4'
          - '1.5'
          - '1.6.3'
          - '1.7.2'
          - '1.8'
          - '1.9.1'
          - '1.10'
          - '1.11.1'
          - '1.12'
          - '1.13.1'
          - '2.0.2'
        lua_version:
          - '5.1.5'
          - '5.2.4'
          - '5.3.6'
          - '5.4.7'
        compiler:
          - { cc: 'gcc', cxx: 'g++' }
          - { cc: 'clang', cxx: 'clang++' }

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install lua ${{ matrix.lua_version }}
        uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: ${{ matrix.lua_version }}

      - name: install taglib ${{ matrix.taglib_version }}
        run: perl testsuite/install-taglib.pl ${{ matrix.taglib_version }}
      
      - name: configure lua-taglib
        env:
          PKG_CONFIG_LIBDIR: ''
          CC: ${{ matrix.compiler.cc }}
          CXX: ${{ matrix.compiler.cxx }}
        run: cmake -DLUA_INCLUDE_DIR=$(pwd)/.lua/include -DLUA_LIBRARY=$(pwd)/.lua/lib/liblua.a -DTAGLIB_INCLUDE_DIR=$(pwd)/.taglib/include/taglib -DTAGLIB_LIBRARY=$(pwd)/.taglib/lib/libtag.so -B build

      - name: build lua-taglib
        run: make -C build
