#ifndef LTAGLIB_TAGLIB_INCLUDE_GUARD
#define LTAGLIB_TAGLIB_INCLUDE_GUARD

#include <taglib.h>

#define LTAGLIB_VERSION_NUM(MAJOR, MINOR, PATCH) ( (MAJOR << 16) | (MINOR << 8) | PATCH )
#define LTAGLIB_VERSION (LTAGLIB_VERSION_NUM(TAGLIB_VERSION_MAJOR, TAGLIB_VERSION_MINOR, TAGLIB_VERSION_PATCH))

/* convenience macros */
#define LTAGLIB_1_2   (LTAGLIB_VERSION_NUM(1,2,0))
#define LTAGLIB_1_3   (LTAGLIB_VERSION_NUM(1,3,0))
#define LTAGLIB_1_4   (LTAGLIB_VERSION_NUM(1,4,0))
#define LTAGLIB_1_5   (LTAGLIB_VERSION_NUM(1,5,0))
#define LTAGLIB_1_6   (LTAGLIB_VERSION_NUM(1,6,0))
#define LTAGLIB_1_7   (LTAGLIB_VERSION_NUM(1,7,0))
#define LTAGLIB_1_8   (LTAGLIB_VERSION_NUM(1,8,0))
#define LTAGLIB_1_9   (LTAGLIB_VERSION_NUM(1,9,0))
#define LTAGLIB_1_10 (LTAGLIB_VERSION_NUM(1,10,0))
#define LTAGLIB_1_11 (LTAGLIB_VERSION_NUM(1,11,0))
#define LTAGLIB_1_12 (LTAGLIB_VERSION_NUM(1,12,0))
#define LTAGLIB_1_13 (LTAGLIB_VERSION_NUM(1,13,0))
#define LTAGLIB_2_0   (LTAGLIB_VERSION_NUM(2,0,0))
#define LTAGLIB_2_1   (LTAGLIB_VERSION_NUM(2,1,0))
#define LTAGLIB_2_2   (LTAGLIB_VERSION_NUM(2,2,0))

#define LTAGLIB_ATLEAST(v)  (LTAGLIB_VERSION >= v)
#define LTAGLIB_UNDER(v) (LTAGLIB_VERSION < v)

#include "shared/lua.h"

extern "C" {

LTAGLIB_PUBLIC
int luaopen_TagLib(lua_State *L);

}

#endif

